version: 2.1

workflows:
  version: 2
  one:
    jobs:
      - build
      - release:
          context: cambridge-asm
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/rust:1.57
    steps:
      - checkout
      - run:
          name: build
          command: cargo build && cargo build --all-features
      - run:
          name: test
          command: cargo test && cargo test --all-features
  release:
    docker:
      - image: saadisave/cambridge-asm-ci:0.1.0
        auth:
          username: saadisave
          password: $DOCKER_AUTH
    steps:
      - checkout
      - run:
          name: gh login
          command: echo $GITHUB_TOKEN | gh auth login --with-token
      - run:
          name: cargo login
          command: cargo login $CARGO_API_TOKEN
      - run:
          name: crates.io publish
          command: cargo publish
      - run:
          name: buildall
          command: python3 .circleci/release.py
      - run:
          name: GitHub release
          command: gh release create -t cambridge-asm-`git describe --tags --abbrev=0` *.zip
