name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:1.57-slim

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --verbose && cargo test --all-features --verbose
