name: Publish lib

on:
  push:
    tags:
      - "lib-[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish lib
    runs-on: ubuntu-latest
    container: ghcr.io/saadisave/cambridge-asm-ci:latest
    environment: Release
    needs: test

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git config --system --add safe.directory /__w/cambridge-asm/cambridge-asm

      - name: Cargo login
        run: cargo login ${{ secrets.CARGO_API_TOKEN }}

      - name: Publish crate
        run: cargo publish -p cambridge-asm
