name: Publish ghcr

on:
  push:
    tags:
      - 'podman-[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch tags
        run: git fetch --unshallow

      - name: Set release version
        run: export RELEASE_VERSION=$(python3 .github/getversion.py)

      - name: Build container
        run: podman build -t "ghcr.io/saadisave/cambridge-asm-ci:${{ env.RELEASE_VERSION }}" .docker

      - name: Add tag
        run: podman image tag "ghcr.io/saadisave/cambridge-asm-ci:${{ env.RELEASE_VERSION }}" ghcr.io/saadisave/cambridge-asm-ci:latest
 
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u=saadisave --password-stdin
      
      - name: Push
        run: podman push "ghcr.io/saadisave/cambridge-asm-ci:${{ env.RELEASE_VERSION }}" && podman push ghcr.io/saadisave/cambridge-asm-ci:latest
