name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: ghcr.io/saadisave/cambridge-asm-ci:latest
    environment: Release

    steps:
      - uses: actions/checkout@v2

      - name: Fetch tags
        run: git fetch --unshallow

      - name: Set release version
        run: export RELEASE_VERSION=`git describe --tags --abbrev=0` && echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Run tests
        run: cargo test && cargo test --all-features

      - name: Cargo login
        run: cargo login ${{ secrets.CARGO_API_TOKEN }}

      - name: Release crate
        run: cargo publish

      - name: Build all
        run: python3 .github/buildall.py

      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Release
        run: gh release create ${{ env.RELEASE_VERSION }} -t "cambridge-asm-${{ env.RELEASE_VERSION }}" release/*
