name: Test

on:
  push:
    paths:
      - 'cambridge-asm/**'
      - 'cambridge-asm-cli/**'
  pull_request:
    paths:
      - 'cambridge-asm/**'
      - 'cambridge-asm-cli/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/saadisave/cambridge-asm-ci:latest

    steps:
      - uses: actions/checkout@v2

      - name: Check format
        run: cargo fmt --check

      - name: Run in debug mode
        run: cargo hack test --feature-powerset && cargo hack build --feature-powerset
      
      - name: Run in release mode
        run: cargo hack test --release --feature-powerset && cargo hack build --release --feature-powerset
