name: Test

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "cli/**"
  pull_request:
    paths:
      - "lib/**"
      - "cli/**"
  workflow_call:
    inputs:
      package:
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/saadisave/cambridge-asm-ci:latest
    env:
      package-arg: ${{ format('{0}{1}', inputs.package != '' && '-p ' || '', inputs.package) }}

    steps:
      - uses: actions/checkout@v3

      - name: Check format
        run: cargo fmt --check

      - name: Run clippy
        run: cargo hack ${{ env.package-arg }} --feature-powerset clippy

      - name: Run in debug mode
        run: cargo hack test ${{ env.package-arg }} --feature-powerset && cargo hack build ${{ env.package-arg }} --feature-powerset

      - name: Run in release mode
        run: cargo hack test ${{ env.package-arg }} --release --feature-powerset && cargo hack build ${{ env.package-arg }} --release --feature-powerset
